### ISSUE TITLE
Error in 0203-run-SIS

### ISSUE THREAD

**Issue by EleonoraMilea** [IBAHCM/JumaMinya_series02#1]
Hey, it is giving me this error when it gets to the end to the plotting functions (lines 178, 181,182:
"Error in plot.window(...) : need finite 'ylim' values"

All the others work fine!

**Comment by JumaMinya** [comment]
@EleonoraMilea which practical is that giving such errors??

**Comment by JumaMinya** [comment]
Sorry, Seen, I hope you mean 0203-run-SIS??

**Comment by JumaMinya** [comment]
I will check that.

**Comment by EleonoraMilea** [comment]
yes, in 0203-run-SIS.

**Comment by JumaMinya** [comment]
All are fine, I was unable to see Practical 2-4 so I suspect you are finalizing that.

**Comment by EleonoraMilea** [comment]
I will check again 0203 and raise another issue (not sure what you mean you are unable to see 2.4?)

**Comment by EleonoraMilea** [comment]
it still giving me the same error message

**Comment by JumaMinya** [comment]
In the files that I pulled; your files for practical 2-4 (ie 0204-deterministic-SIR.R and 0204-run-SIR.R) could not be seen, So my thinking is that you are still working on them

**Comment by EleonoraMilea** [comment]
could you please raise an issue in my repository? :) so we don't mix things up

**Comment by JumaMinya** [comment]
@EleonoraMilea 
I failed to resolve the error "Error in plot.window(...) : need finite 'ylim' values"
Seeking an intervention

**Comment by EleonoraMilea** [comment]
I think it is your code in the " run "document... It looks like you have created the timesteps object for the timestep_deterministic_SIS function, which I don't think is needed, and it also seems that you run the function twice.

**Comment by EleonoraMilea** [comment]
All code is working now! :)

**Comment by JumaMinya** [comment]
@EleonoraMilea 
Thanks
