### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by richardreeve** [IBAHCM/JumaMinya_series02#2]
You've done some great work in places here. In particular you're
the only person to have correctly recorded the values from runs in 2.1
and put them into your table directly. Really well done for that -
it's much better than copying the actual numbers manually into the table.

However, you need a bit more attention to the reports - you forgot to
add `library(knitr)` to 2.1, so `kable()` doesn't run. And your
reports don't create the right headers because you're missing the 1st
line:

```r
#' ---
```

which tells the report generator that this is the header about to
start (just like the identical bit at the end of the header). If you
fix these small issues. In the functions your reports
don't generate because you have `#'` text blocks inside the function
definitions. If you tidy that up a bit you should be able to generate
nice reports throughout.

Some other files don't generate reports either. I don't know why but
if you select the whole file and reindent it (Ctrl-i or Command-i) and
then it works for me.

Finally you use column names `susceptibles` and `susceptible` in
different places (and infected and recovered) - this happens to work, but I
suspect it's an accident - fix it or be very careful.

**Comment by JumaMinya** [comment]
@richardreeve 
Thanks,
I have incorporated all the feedback provided.
